server:
  port: 8082

tomcat:
  uri-encoding: UTF-8

spring:
  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 100MB






#logo-img:
#  request-path: /image/**
#  local-path: C:/fileInfo/


